### ISSUE TITLE
Incorrect function documentation

### ISSUE THREAD

**Issue by andrewthetechie** [ludeeus/aiogithubapi#116]
## The problem
set_last_commit() has incorrect function documentation. This causes incorrect documentation to be generated in the netlify docs too.

## Problem-relevant code
https://github.com/ludeeus/aiogithubapi/blob/565bb948152eac921b5e26117d58aa23936cbf30/aiogithubapi/objects/repository/__init__.py#L175

## Additional Info

This appears to be a duplicate of the function documentation for get_releases() 
https://github.com/ludeeus/aiogithubapi/blob/565bb948152eac921b5e26117d58aa23936cbf30/aiogithubapi/objects/repository/__init__.py#L152-L155

**Comment by ludeeus** [comment]
Please do not use anything under the `objects` directory.
See <https://github.com/ludeeus/aiogithubapi#project-transition>

To get the last commit sha of a repository use:

```python
from aiogithubapi import GitHubAPI

async def some_async_function():
    client = GitHubAPI(token=GITH_UB_API_TOKEN)
    response = await client.repos.list_commits()
    last_commit = response.data[0].sha
```

Until the transition period is completed, there will be old/stale information, sorry about that.

**Comment by andrewthetechie** [comment]
This doesn't fix that the documentation of the function is incorrect.

I wasn't using it directly, just reading through the codebase to understand it.
