### ISSUE TITLE
Unsubscribe will not actually cancel the background task

### ISSUE THREAD

**Issue by elupus** [ludeeus/aiogithubapi#154]
## The problem

Event unsubscribe will not actually stop the subscription, only the call_later handle will be cancelled, which has likely already executed and create the task.

Noticed in: https://github.com/home-assistant/core/pull/82475 and more specifically when adding: https://github.com/home-assistant/core/pull/82475/commits/c7f0e11a01d0b8a501965abb7b064e57d21bfd6a

- https://github.com/ludeeus/aiogithubapi/blob/178d28d253453e6fcc16c30a4418f042273d62a0/aiogithubapi/namespaces/events.py#L137
- https://github.com/ludeeus/aiogithubapi/blob/178d28d253453e6fcc16c30a4418f042273d62a0/aiogithubapi/namespaces/events.py#L155

## Environment

- Operating system: Any
- Python version: Any

## Problem-relevant code

```python

```

## Traceback/Error logs

```txt
    @pytest.fixture(autouse=True)
    def verify_cleanup(event_loop: asyncio.AbstractEventLoop):
        """Verify that the test has cleaned up resources correctly."""
        threads_before = frozenset(threading.enumerate())
        tasks_before = asyncio.all_tasks(event_loop)
        yield
    
        event_loop.run_until_complete(event_loop.shutdown_default_executor())
    
        if len(INSTANCES) >= 2:
            count = len(INSTANCES)
            for inst in INSTANCES:
                inst.stop()
            pytest.exit(f"Detected non stopped instances ({count}), aborting test run")
    
        threads = frozenset(threading.enumerate()) - threads_before
        for thread in threads:
            assert isinstance(thread, threading._DummyThread)
    
        tasks = asyncio.all_tasks(event_loop) - tasks_before
>       assert not tasks
E       AssertionError: assert not {<Task pending name='Task-19' coro=<_GitHubEventsBaseNamespace.subscribe.<locals>._subscriber() running at /Users/joak...aiogithubapi/namespaces/events.py:132> wait_for=<Future pending cb=[<TaskWakeupMethWrapper object at 0x116c73d60>()]>>}
```

**Comment by ludeeus** [comment]
It does cancel all future requests, but it does not force-stop any ongoing requests.

**Comment by elupus** [comment]
Yup, meaning during tests these tended to leak over logs to next test. We now stop them manually. But would be better if it cleaned up fully when unloaded.

Its not causing any issues now though, so its up to you if you want to fix it or not.

**Comment by ludeeus** [comment]
Ill look into adding a new async method to stop all and only return when everything is done.
That should be added to `__aexit__` anyway for those that uses `async with ....`
