### ISSUE TITLE
'NoneType' object has no attribute 'items' - aiogithubapi/models/base.py", line 35, in __init__

### ISSUE THREAD

**Issue by CloCkWeRX** [ludeeus/aiogithubapi#174]
## The problem

Certain responses from github can omit the structure(s) that are expected.

https://github.com/ludeeus/aiogithubapi/blob/main/aiogithubapi/models/base.py#L35

This code should probably check the argument `data` conforms and if not, raise a meaningful exception

## Environment

- Operating system:
- Python version:

## Problem-relevant code

```python

```

## Traceback/Error logs

This error originated from a custom integration.

Logger: custom_components.hacs
Source: custom_components/hacs/base.py:497
Integration: HACS (documentation, issues)
First occurred: January 2, 2023 at 2:08:30 PM (1 occurrences)
Last logged: January 2, 2023 at 2:08:30 PM
```
'NoneType' object has no attribute 'items'
Traceback (most recent call last):
  File "/config/custom_components/hacs/base.py", line 497, in async_github_api_method
    return await method(*args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/aiogithubapi/namespaces/contents.py", line 62, in get
    response.data = GitHubContentsModel(response.data)
  File "/usr/local/lib/python3.10/site-packages/aiogithubapi/models/base.py", line 35, in __init__
    for key, value in self._raw_data.items():
AttributeError: 'NoneType' object has no attribute 'items'
```

**Comment by ludeeus** [comment]
> Certain responses from github can omit the structure(s) that are expected.

Where is that documented?
Why did you skip filling out the template?
